title: EchoNarrator [MICCAI2024]
logo: /assets/img/logo.png
description: Generating natural text explanations for ejection fraction predictions
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
